# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О нас', max_length=200, verbose_name='О нас')),
                ('title_ky', models.CharField(default='О нас', max_length=200, null=True, verbose_name='О нас')),
                ('title_ru', models.CharField(default='О нас', max_length=200, null=True, verbose_name='О нас')),
                ('title_en', models.CharField(default='О нас', max_length=200, null=True, verbose_name='О нас')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('youtube_video_url', models.URLField(verbose_name='URL видео с YouTube')),
                ('youtube_video_url_ky', models.URLField(null=True, verbose_name='URL видео с YouTube')),
                ('youtube_video_url_ru', models.URLField(null=True, verbose_name='URL видео с YouTube')),
                ('youtube_video_url_en', models.URLField(null=True, verbose_name='URL видео с YouTube')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='AboutUsConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('surname_ky', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('surname_ru', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('surname_en', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('name_ky', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('whatsapp', models.URLField(verbose_name='whatsapp')),
                ('whatsapp_ky', models.URLField(null=True, verbose_name='whatsapp')),
                ('whatsapp_ru', models.URLField(null=True, verbose_name='whatsapp')),
                ('whatsapp_en', models.URLField(null=True, verbose_name='whatsapp')),
                ('telegram', models.URLField(verbose_name='telegram')),
                ('telegram_ky', models.URLField(null=True, verbose_name='telegram')),
                ('telegram_ru', models.URLField(null=True, verbose_name='telegram')),
                ('telegram_en', models.URLField(null=True, verbose_name='telegram')),
                ('instagram', models.URLField(verbose_name='instagram')),
                ('instagram_ky', models.URLField(null=True, verbose_name='instagram')),
                ('instagram_ru', models.URLField(null=True, verbose_name='instagram')),
                ('instagram_en', models.URLField(null=True, verbose_name='instagram')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный консультант')),
            ],
            options={
                'verbose_name': 'Консультант',
                'verbose_name_plural': 'Консультанты',
            },
        ),
        migrations.CreateModel(
            name='AboutUsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about_images/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': "Изображение для 'О нас'",
                'verbose_name_plural': "Изображения для 'О нас'",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutUsInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Запрос на консультацию',
                'verbose_name_plural': 'Запросы на консультации',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('question_ky', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_ky', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(null=True, verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ',
                'verbose_name_plural': 'Вопросы-Ответы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('content_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('content_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Условия возврата',
                'verbose_name_plural': 'Условия возврата',
            },
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержание')),
                ('content_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'Пользовательское соглашение',
                'verbose_name_plural': 'Пользовательские соглашения',
            },
        ),
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши Проекты', max_length=200, verbose_name='Заголовок')),
                ('title_ky', models.CharField(default='Наши Проекты', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(default='Наши Проекты', max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(default='Наши Проекты', max_length=200, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('youtube_video_url', models.URLField(verbose_name='URL видео с YouTube')),
                ('youtube_video_url_ky', models.URLField(null=True, verbose_name='URL видео с YouTube')),
                ('youtube_video_url_ru', models.URLField(null=True, verbose_name='URL видео с YouTube')),
                ('youtube_video_url_en', models.URLField(null=True, verbose_name='URL видео с YouTube')),
                ('tours', models.ManyToManyField(related_name='our_projects', to='tours.tour', verbose_name='Связанные туры')),
            ],
            options={
                'verbose_name': 'Наши проекты',
                'verbose_name_plural': 'Наши проекты',
            },
        ),
    ]
