# Generated by Django 5.0.6 on 2024-10-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос-Ответ', 'verbose_name_plural': 'Вопросы-Ответы'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='order',
        ),
    ]
