# Generated by Django 5.0.6 on 2024-10-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_faq_options_remove_faq_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(help_text='Вопрос', max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(help_text='Вопрос', max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ky',
            field=models.CharField(help_text='Вопрос', max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(help_text='Вопрос', max_length=255, null=True, verbose_name='Вопрос'),
        ),
    ]
