# Generated by Django 5.0.6 on 2024-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_faq_question_alter_faq_question_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='youtube_video_url_en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='youtube_video_url_ky',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='youtube_video_url_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='instagram_en',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='instagram_ky',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='instagram_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='surname_en',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='surname_ky',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='surname_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='telegram_en',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='telegram_ky',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='telegram_ru',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='whatsapp_en',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='whatsapp_ky',
        ),
        migrations.RemoveField(
            model_name='aboutusconsultant',
            name='whatsapp_ru',
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='youtube_video_url_en',
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='youtube_video_url_ky',
        ),
        migrations.RemoveField(
            model_name='ourprojects',
            name='youtube_video_url_ru',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
    ]
