# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=50, verbose_name='Заголовок')),
                ('title_ky', models.CharField(default='Контакты', max_length=50, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(default='Контакты', max_length=50, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(default='Контакты', max_length=50, null=True, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('description_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('description_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('job', models.CharField(max_length=200, verbose_name='Режим работы')),
                ('job_ky', models.CharField(max_length=200, null=True, verbose_name='Режим работы')),
                ('job_ru', models.CharField(max_length=200, null=True, verbose_name='Режим работы')),
                ('job_en', models.CharField(max_length=200, null=True, verbose_name='Режим работы')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
                ('address_ky', models.CharField(max_length=150, null=True, verbose_name='Адрес')),
                ('address_ru', models.CharField(max_length=150, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(max_length=150, null=True, verbose_name='Адрес')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='WhatsApp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
