# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='', verbose_name='Иконка')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Преимущество работы с нами',
                'verbose_name_plural': 'Преимущества работы с нами',
            },
        ),
        migrations.CreateModel(
            name='RentOfCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Аренда автомобиля', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Аренда автомобиля',
                'verbose_name_plural': 'Аренда автомобилей',
            },
        ),
        migrations.CreateModel(
            name='BestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.ManyToManyField(related_name='best_choices', to='tours.tour', verbose_name='Туры')),
            ],
            options={
                'verbose_name': 'Лучшее предложение',
                'verbose_name_plural': 'Лучшие предложения',
            },
        ),
        migrations.CreateModel(
            name='PopularHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels', models.ManyToManyField(related_name='popular_hotels', to='hotels.hotel', verbose_name='Отели')),
            ],
            options={
                'verbose_name': 'Популярный отель',
                'verbose_name_plural': 'Популярные отели',
            },
        ),
        migrations.CreateModel(
            name='RentOfCarDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('rent_of_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='main.rentofcar', verbose_name='Аренда автомобиля')),
            ],
            options={
                'verbose_name': 'Описание аренды автомобиля',
                'verbose_name_plural': 'Описания аренды автомобилей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RentOfCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_rentals/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('rent_of_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.rentofcar', verbose_name='Аренда автомобиля')),
            ],
            options={
                'verbose_name': 'Изображение аренды автомобиля',
                'verbose_name_plural': 'Изображения аренды автомобилей',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RestIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.ManyToManyField(related_name='rest_ideas', to='tours.tour', verbose_name='Туры')),
            ],
            options={
                'verbose_name': 'Идея для отдыха',
                'verbose_name_plural': 'Идеи для отдыха',
            },
        ),
    ]
