# Generated by Django 5.0.6 on 2024-10-09 19:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefits',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='benefits',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='benefits',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='benefits',
            name='title_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='benefits',
            name='title_ky',
            field=models.CharField(max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='benefits',
            name='title_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='rentofcar',
            name='title_en',
            field=models.CharField(default='Аренда автомобиля', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='rentofcar',
            name='title_ky',
            field=models.CharField(default='Аренда автомобиля', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='rentofcar',
            name='title_ru',
            field=models.CharField(default='Аренда автомобиля', max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='rentofcardescription',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='rentofcardescription',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='rentofcardescription',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание'),
        ),
    ]
