# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('main_image', models.ImageField(upload_to='blog_images/', verbose_name='Главное изображение')),
                ('second_title', models.CharField(max_length=200, verbose_name='Второй заголовок')),
                ('second_title_ky', models.CharField(max_length=200, null=True, verbose_name='Второй заголовок')),
                ('second_title_ru', models.CharField(max_length=200, null=True, verbose_name='Второй заголовок')),
                ('second_title_en', models.CharField(max_length=200, null=True, verbose_name='Второй заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое')),
                ('content_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Содержимое')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержимое')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержимое')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое')),
                ('content_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Содержимое')),
                ('content_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Содержимое')),
                ('content_en', ckeditor.fields.RichTextField(null=True, verbose_name='Содержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_section_images/', verbose_name='Картинка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blogpost', verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Раздел блога',
                'verbose_name_plural': 'Разделы блога',
                'ordering': ['order'],
            },
        ),
    ]
