# Generated by Django 5.0.6 on 2024-10-10 01:05

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='main_image',
            field=models.ImageField(upload_to='blog_images/', validators=[blog.models.validate_file_size], verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='blogsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_section_images/', validators=[blog.models.validate_file_size], verbose_name='Картинка'),
        ),
    ]
