# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsAfterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_city_country', models.FileField(upload_to='', verbose_name='Иконка для "Город/Страна"')),
                ('icon_date', models.FileField(upload_to='', verbose_name='Иконка для даты "Туда/Обратно"')),
            ],
            options={
                'verbose_name': 'Иконка после названия',
                'verbose_name_plural': 'Иконки после названия',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название тура')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('start_tour', models.DateField(verbose_name='Начало сезона')),
                ('end_tour', models.DateField(verbose_name='Конец сезона')),
                ('departure_date', models.DateField(verbose_name='Дата вылета')),
                ('nights', models.PositiveIntegerField(verbose_name='Количество ночей')),
                ('manual_rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Ручной рейтинг')),
                ('average_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('is_best_choice', models.BooleanField(default=False, verbose_name='Лучшее предложение')),
                ('is_rest_idea', models.BooleanField(default=False, verbose_name='Идея для отдыха')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours_from', to='common.city', verbose_name='Откуда')),
                ('tags', models.ManyToManyField(related_name='tours', to='common.tag', verbose_name='Теги')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours_to', to='common.city', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='TourComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.comments')),
                ('tour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='tours.tour', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Отзыв о туре',
                'verbose_name_plural': 'Отзывы о турах',
            },
            bases=('common.comments',),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/', verbose_name='Фото')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Изображение тура',
                'verbose_name_plural': 'Изображения туров',
            },
        ),
        migrations.CreateModel(
            name='TourInquiry',
            fields=[
                ('inquiry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.inquiry')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tours.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Запрос на информацию о туре',
                'verbose_name_plural': 'Запросы на информацию о турах',
            },
            bases=('common.inquiry',),
        ),
    ]
