# Generated by Django 5.0.6 on 2024-10-09 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_description_en_tour_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
