# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsAfterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_city_country', models.FileField(upload_to='', verbose_name='Иконка для "Страна/Город"')),
                ('location_text', models.CharField(default='Находится в центре', max_length=30, verbose_name='Находится в центре')),
                ('icon_location', models.FileField(upload_to='', verbose_name='Иконка для "Местоположения(Находится в центре)"')),
            ],
            options={
                'verbose_name': 'Иконка после названия',
                'verbose_name_plural': 'Иконки после названия',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название отеля')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('arrival_date', models.DateField(verbose_name='Дата заезда')),
                ('departure_date', models.DateField(verbose_name='Дата выезда')),
                ('nights', models.PositiveIntegerField(verbose_name='Количество ночей')),
                ('manual_rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Ручной рейтинг')),
                ('average_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('is_popular_hotel', models.BooleanField(default=False, verbose_name='Популярный отель')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_from', to='common.city', verbose_name='Город')),
                ('tags', models.ManyToManyField(related_name='hotels', to='common.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='PopularHotels',
            fields=[
            ],
            options={
                'verbose_name': 'Популярный отель',
                'verbose_name_plural': 'Популярные отели',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hotels.hotel',),
        ),
        migrations.CreateModel(
            name='HotelComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.comments')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='hotels.hotel', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Отзыв об отеле',
                'verbose_name_plural': 'Отзывы об отелях',
            },
            bases=('common.comments',),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/', verbose_name='Фото')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Изображение отеля',
                'verbose_name_plural': 'Изображения отелей',
            },
        ),
        migrations.CreateModel(
            name='HotelInquiry',
            fields=[
                ('inquiry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.inquiry')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Запрос на информацию об отеле',
                'verbose_name_plural': 'Запросы на информацию об отелях',
            },
            bases=('common.inquiry',),
        ),
    ]
