# Generated by Django 5.0.6 on 2024-10-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_description_en_hotel_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
