# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsAfterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_city_country', models.FileField(upload_to='', verbose_name='Иконка для "Страна/Город"')),
                ('location_text', models.CharField(default='Находится в центре', max_length=30, verbose_name='Находится в центре')),
                ('icon_location', models.FileField(upload_to='', verbose_name='Иконка для "Местоположения(Находится в центре)"')),
            ],
            options={
                'verbose_name': 'Иконка после названия',
                'verbose_name_plural': 'Иконки после названия',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('departure_date', models.DateField(verbose_name='Дата получения')),
                ('return_date', models.DateField(verbose_name='Дата возврата')),
                ('passengers', models.PositiveIntegerField(verbose_name='Количество пассажиров')),
                ('manual_rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Ручной рейтинг')),
                ('average_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_city', to='common.city', verbose_name='Город')),
                ('tags', models.ManyToManyField(related_name='transfers', to='common.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Трансфер',
                'verbose_name_plural': 'Трансферы',
            },
        ),
        migrations.CreateModel(
            name='TransferComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.comments')),
                ('transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='transfer.transfer', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Отзыв о трансфере',
                'verbose_name_plural': 'Отзывы о трансферах',
            },
            bases=('common.comments',),
        ),
        migrations.CreateModel(
            name='TransferImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='transfer_images/', verbose_name='Фото')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='transfer.transfer', verbose_name='Трансфер')),
            ],
            options={
                'verbose_name': 'Изображение трансфера',
                'verbose_name_plural': 'Изображения трансферов',
            },
        ),
        migrations.CreateModel(
            name='TransferInquiry',
            fields=[
                ('inquiry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.inquiry')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='transfer.transfer', verbose_name='Трансфер')),
            ],
            options={
                'verbose_name': 'Запрос на информацию о трансфере',
                'verbose_name_plural': 'Запросы на информацию о трансферах',
            },
            bases=('common.inquiry',),
        ),
    ]
