# Generated by Django 5.0.6 on 2024-10-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_transfer_description_en_transfer_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
