# Generated by Django 5.0.6 on 2024-10-09 14:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='comments',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя-Фамилия'),
        ),
        migrations.AddField(
            model_name='comments',
            name='full_name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя-Фамилия'),
        ),
        migrations.AddField(
            model_name='comments',
            name='full_name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя-Фамилия'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='comments',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Комментарий'),
        ),
    ]
