JAZZMIN_SETTINGS = {
    "site_title": "Название вашего сайта",
    "site_header": "Название вашего сайта",
    "site_logo_classes": "img-circle",
    "site_brand": "Atlas Travel",
    "welcome_sign": "Добро пожаловать в админ-панель вашего сайта",
    "copyright": "Ваше авторское право",
    "search_model": [],
    "topmenu_links": [

    ],
    "default_icon_parents": "fas fa-circle",
    "default_icon_children": "fas fa-dot-circle",
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
    "changeform_format_overrides": {
    },
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "services.VisaService": "fas fa-passport",
        "services.ServiceImage": "fas fa-image",
        "services.ServiceFeature": "fas fa-list-ul",

        "main.RestIdea": "fas fa-lightbulb",
        "main.BestChoice": "fas fa-trophy",
        "main.PopularHotel": "fas fa-hotel",
        "main.RentOfCar": "fas fa-car",
        "main.RentOfCarImage": "fas fa-car-side",
        "main.RentOfCarDescription": "fas fa-file-alt",
        "main.Benefits": "fas fa-gift",

        "hotels.HotelComments": "fas fa-comment-alt",
        "hotels.Hotel": "fas fa-hotel",
        "hotels.PopularHotels": "fas fa-star",
        "hotels.HotelImage": "fas fa-image",
        "hotels.HotelInquiry": "fas fa-question-circle",
        "hotels.IconsAfterName": "fas fa-icons",

        "flights.FlightComments": "fas fa-comment-alt",
        "flights.Flight": "fas fa-plane",
        "flights.FlightImage": "fas fa-image",
        "flights.FlightInquiry": "fas fa-question-circle",
        "flights.IconsAfterName": "fas fa-icons",

        "contacts.Contacts": "fas fa-address-book",

        "blog.BlogPost": "fas fa-blog",
        "blog.BlogSection": "fas fa-newspaper",

        "about.AboutUs": "fas fa-info-circle",
        "about.AboutUsImage": "fas fa-image",
        "about.FAQ": "fas fa-question",
        "about.AboutUsInquiry": "fas fa-envelope",
        "about.AboutUsConsultant": "fas fa-user-tie",
        "about.OurProjects": "fas fa-project-diagram",
        "about.PrivacyPolicy": "fas fa-user-shield",
        "about.UserAgreement": "fas fa-handshake",
        "about.ReturnPolicy": "fas fa-undo",

        "tours.Tour": "fas fa-plane-departure",
        "tours.TourComments": "fas fa-comment-alt",
        "tours.TourImage": "fas fa-image",
        "tours.TourInquiry": "fas fa-question-circle",
        "tours.IconsAfterName": "fas fa-icons",

        "common.Tag": "fas fa-tag",
        "common.City": "fas fa-city",
        "common.Country": "fas fa-globe",
        "common.Comments": "fas fa-comments",
        "common.Inquiry": "fas fa-envelope",

        "transfer.Transfer": "fas fa-shuttle-van",
        "transfer.TransferComments": "fas fa-comment-alt",
        "transfer.TransferImage": "fas fa-image",
        "transfer.TransferInquiry": "fas fa-question-circle",
        "transfer.IconsAfterName": "fas fa-icons",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": True,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
    "actions_sticky_top": True,
}