# Generated by Django 5.0.6 on 2024-10-08 23:01

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsAfterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_city_country', models.FileField(upload_to='', verbose_name='Иконка для "Откуда/Куда"')),
                ('icon_date', models.FileField(upload_to='', verbose_name='Иконка для даты "Туда/Обратно"')),
            ],
            options={
                'verbose_name': 'Иконка после названия',
                'verbose_name_plural': 'Иконки после названия',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название рейса')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('departure_date', models.DateField(verbose_name='Дата вылета')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('passengers', models.PositiveIntegerField(verbose_name='Количество пассажиров')),
                ('class_type', models.CharField(choices=[('economy', 'Эконом'), ('business', 'Бизнес')], max_length=50, verbose_name='Класс обслуживания')),
                ('manual_rating', models.FloatField(blank=True, default=None, null=True, verbose_name='Ручной рейтинг')),
                ('average_rating', models.FloatField(default=0, verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_from', to='common.city', verbose_name='Откуда')),
                ('tags', models.ManyToManyField(related_name='flights', to='common.tag', verbose_name='Теги')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights_to', to='common.city', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Авиаперелет',
                'verbose_name_plural': 'Авиаперелеты',
            },
        ),
        migrations.CreateModel(
            name='FlightComments',
            fields=[
                ('comments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.comments')),
                ('flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='flights.flight', verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Отзыв на авиаперелет',
                'verbose_name_plural': 'Отзывы на авиаперелеты',
            },
            bases=('common.comments',),
        ),
        migrations.CreateModel(
            name='FlightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flight_images/', verbose_name='Фото')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flights.flight', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Изображение авиаперелета',
                'verbose_name_plural': 'Изображения авиаперелетов',
            },
        ),
        migrations.CreateModel(
            name='FlightInquiry',
            fields=[
                ('inquiry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.inquiry')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='flights.flight', verbose_name='Запросы')),
            ],
            options={
                'verbose_name': 'Запрос на информацию об авиаперелете',
                'verbose_name_plural': 'Запросы на информацию об авиаперелетах',
            },
            bases=('common.inquiry',),
        ),
    ]
