# Generated by Django 5.0.6 on 2024-10-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_description_en_flight_description_ky_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightimage',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
    ]
